### ISSUE TITLE
output folder for workspace

### ISSUE THREAD

**Issue by qRoC** [Joining7943/iai-callgrind#4]
Hi, thanks for the fork!.

**Problem:**

iai creates `target/iai` in the workspace member.

**Expected:**

```
/workspace/
    /member1/{src,benches}
    /member2/{src,benches}
   /target/
    /iai/
    /criterion/
    /...
```

**Actual:**

```
/workspace/
    /member1/{src,benches,target/iai}
    /member2/{src,benches,target/iai}
   /target/
    /iai/
    /criterion/
    /...
```

**Comment by Joining7943** [comment]
Thanks for reporting this. You're right, the output directory should be different. Here's the solution I came up with:

1. Try `CARGO_TARGET_DIR`
2. Try to get the target directory from `cargo metadata`, which usually is the `/workspace/target` directory in the workspace root.
3. Use `./target` as before if none of the above was successful.

Then comes the `iai` directory and if possible `CARGO_PKG_NAME` (member1, member2, ...) of the currently benchmarked package. So, you're example should now look as expected:

```
/workspace/
    /member1/{src,benches}
    /member2/{src,benches}
    /target/
      /iai/$CARGO_PKG_NAME/
      /criterion/
      /...
```
